using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Common
{
    public class Car
    {
        #region Attributes
        private int id = default; // 4 Bytes
        private string? model = default; // 4 Bytes For Address
        private double speed = default; // 8 Bytes
        private double price = default; // 8 Bytes
        private string number = default;// 4 Bytes For Address

        #endregion

        #region Properties
        public void SetPrice(double price)
        {
            if (price >= 5000)
                price = price;
            else
                price = 5000;
        }

        public double GetPrice() { return price; }
        #endregion

        #region Constructors
        // Empty Parameterless Constructor [ Default Constructor ]
        // Auto-Generated By Compiler
        public Car() // User Defined Constructor
        {

        }

        public Car(int id, string? model, double speed, double price, string number)
        {
            this.id = id;
            this.model = model;
            this.speed = speed;
            this.price = price;
            this.number = number;
        }
        // Compiler Will No Longer Generate Empty Parameterless Constructor
        #region Constructor Overloading
        public Car(int id, string? model, double speed)
        {
            this.id = id;
            this.model = model;
            this.speed = speed;
            Console.WriteLine("1st Constructor");
        }
        //public Car(int id,string? model)
        //{
        //    this.id=id;
        //    this.model = model;
        //    this.speed = 290;
        //}
        public Car(int id) : this(id, "Audi", 190)
        {
            //this.id = id;
            //this.model = "Audi";
            //this.speed = 190;
            Console.WriteLine("2nd Constructor");
        }
        public Car(int id, string? model) : this(id, model, 270)
        {
            //this.id = id;
            //this.model = "Audi";
            //this.speed = 190;
            Console.WriteLine("3rd Constructor");
        }

        #endregion

        #region Constructor Types

        // Default Constructor : That accept No Input Arguments
        //                     : Sets All Numeric Fields To Zero And All String and Object Fields To Null Within a Class 


        // Parameterized Constructor : Constructor With At Least One Parameter 
        //                           : Can Set Different Values For Each Instance Of the Class


        // Copy Constructor : Copy Variables From Another Object , this Constructor Generates An Object
        //                  : Set the Values Of a New Instance To Those Of An Existing One


        // Private Constructor : Is Created With the Private Specifier 
        //                     : Other Classes Can't Inherit From This Class and It's Impossible to create an instance of this class 
        //                     : Used to Prevent Creating Instance Of Class When There are no Instance Fields or Methods  


        // Static Constructor : Initialize any static Data or To Perform a Particular Action That be performed Only Once 
        //                    : Called Automatically before the first instance is created or any static members are referenced 

        #endregion

        #endregion

        #region Methods
        public void MoveForward()
        {
            price = 10;
            number = "123";
        }

        void Stop()
        {

        }
        public void Display()
        {
            Console.WriteLine($"Number : {number} \t Price : {price}");
        }
        public override string ToString()
        {
            return $"Id = {id} \n Model = {model} \n Speed = {speed}";
        }
        #endregion
    }
}
